### ISSUE TITLE
How to parameterize build?

### ISSUE THREAD

**Issue by tgruenert** [micw/jenkins-k8s-pipeline#3]
Dear @micw !

how can i parameterize a build? A simple checkbox is already shown but the value would be recongnized within build. The Pipeline script look like this:

```
@Library("JenkinsPipeline@v0.7") _
JenkinsPipeline {
    config {
        mavenSettings("some-maven-settings")
        booleanParameter("skipTests","",true)
    }
    maven {
        before{
	     owner.skipTests = params.skipTests
        }
        //skipTests(true)
        enableReleases("master")
        deploy(true)
    }
}
```

Thank you in advance,
;-)

Thomas

**Comment by micw** [comment]
With v1.1, "env" is available in the steps. So you can use:

```
JenkinsPipeline {
    config {
        booleanParameter("skipTests","",true)
    }
    maven {
        skipTests("${env.skipTests?:true}".toBoolean())
    }
}
```

Note that "env.skipTests" is empty on first run (because the "booleanParameter" is not yet created). I I use the "elvis operator" ?: to set "true" as default if env.skipTests is not defined.

**Comment by micw** [comment]
I added this example to the readme
