### ISSUE TITLE
FeatureRequest - labels for steps

### ISSUE THREAD

**Issue by tgruenert** [micw/jenkins-k8s-pipeline#5]
For higher usability some pipelines would nicer with modified labels. See sample picture:
![image](https://user-images.githubusercontent.com/6465773/80375046-eca69200-8897-11ea-8292-339c68a90e8c.png)

for example such a code were helpful:
``` 
docker {
... 
  stepLabel("docker step one")
...
}
```

**Comment by micw** [comment]
Added in version 0.9 with a slightly different syntax:
```
docker "docker step one", {
... 
}
```
